---
title: "STAT167 Final Project - Spring 2023"
authors: "Ryan Solanki, Jake Merrill, Girum Yaye, Harrison Chow, Shuqiao Yu"
date: "2023/5/12"
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: 3
---

#STAT 167 Final Project - Spring 2023

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Required libraries
```{r}
library(tidyverse)
library(CatEncoders)
```

##Loading the dataset of US car accident data
```{r}
library(tidyverse)
# Load subset of LA car accident data
la_accidents <- read_csv("LA_Accidents.csv")
head(la_accidents,5)
```
```{r}
library(CatEncoders)

updatedAccidents2 <- la_accidents[-5:-6]
updatedAccidents2 <- filter(updatedAccidents2, Severity != 1)
updatedAccidents2 <- mutate(updatedAccidents2, Severity = Severity - 1)
colnames(updatedAccidents2)[5] ="Temperature.F."
colnames(updatedAccidents2)[6] ="Visibility.miles."
colnames(updatedAccidents2)[7] ="Wind_Speed.mph."
colnames(updatedAccidents2)[8] ="Precipitation.inches."

updatedAccidents <- la_accidents[-5:-6]
lab_enc = LabelEncoder.fit(updatedAccidents$City)

updatedAccidents$City <- transform(lab_enc, updatedAccidents$City)
updatedAccidents2$City <- transform(lab_enc, updatedAccidents2$City)

lab_enc = LabelEncoder.fit(updatedAccidents$Weather_Condition)

updatedAccidents$Weather_Condition <- transform(lab_enc, updatedAccidents$Weather_Condition)

head(updatedAccidents, 10)
```

```{r}
ggplot(updatedAccidents2) +
  geom_point(aes(x=Wind_Speed.mph., y=Temperature.F., color=factor(Severity))) +
  ggtitle("Scatterplot - Temperature vs Wind Speed") +
  xlab("Wind Speed(Normalized)") +
  ylab("Temperature(Normalized)")
```

```{r}
plotData <- updatedAccidents2 %>% drop_na() %>% select(Severity, Weather_Condition) %>% group_by(Severity, Weather_Condition) %>% summarise(count = n()) %>% filter(count > 1000)
SeverityvsWeatherPlot <- ggplot(data = plotData) +
  geom_col(mapping = aes(x = Severity, y = count, fill = Weather_Condition), position = "dodge") +
  ggtitle("Weather Condition & Severity Plot") + xlab("Severity") + ylab("Severity Count") +
  geom_text(mapping = aes(x = Severity, y = count, fill = Weather_Condition, label = count),hjust = -.1, position = position_dodge(width = .9)) + coord_flip()
  
SeverityvsWeatherPlot
```

```{r}
library(gridExtra)

head(updatedAccidents2, 10)
plot1 <- ggplot(updatedAccidents2, aes(x = Severity, y = Temperature.F.)) +
geom_point() + geom_smooth(method = "lm")
plot2 <- ggplot(updatedAccidents2, aes(x = Severity, y = Wind_Speed.mph.)) +
geom_point() + geom_smooth(method = "lm")
plot3 <- ggplot(updatedAccidents2, aes(x = Severity, y = Visibility.miles.)) +
geom_point() + geom_smooth(method = "lm")
plot3 <- ggplot(updatedAccidents2, aes(x = Severity, y = Visibility.miles.)) +
geom_point() + geom_smooth(method = "lm")
plot4 <- ggplot(updatedAccidents2, aes(x = Severity, y = City)) +
geom_point() + geom_smooth(method = "lm")
plot5 <- ggplot(updatedAccidents2, aes(x = Severity, y = Precipitation.inches.)) +
geom_point() + geom_smooth(method = "lm")
grid.arrange(plot1, plot2, plot3, plot4, plot5, ncol=2)
```

```{r}
storage <- list()
for(i in names(updatedAccidents)[-1]){
  storage[[i]] <- summary(lm(Severity ~ get(i), updatedAccidents))
}
#print(storage)

mlr <- lm(Severity ~ ., updatedAccidents)
summary(mlr)

# updatedAccidents3 <- scale(updatedAccidents[-1:-3])
# updatedAccidents3 <- cbind(updatedAccidents[1:3],updatedAccidents3)
#  
# mlr2 <- lm(Severity ~ Start_Time + End_Time + `Visibility(mi)` + `Wind_Speed(mph)` + Weather_Condition + Junction + Railway + Station + Traffic_Signal, updatedAccidents3)
# summary(mlr2)
```

```{r}
library(dplyr)
library(tidyr)

newDF1 <- updatedAccidents2[ , c("Severity", "Traffic_Calming", "Crossing", "Traffic_Signal")]  

#filtered_df1 <- subset(newDF1, Traffic_Calming != 0)
#filtered_df2 <- subset(newDF1, Traffic_Signal != 0)
#filtered_df3 <- subset(newDF1, Crossing != 0)

newDF1$dbl_col_binned <- cut(newDF1$Severity, breaks = 5, labels = FALSE)
agg_data <- aggregate(Traffic_Calming ~ dbl_col_binned, data = newDF1, FUN = mean)

plot1a <- ggplot(agg_data, aes(x = factor(dbl_col_binned), y = Traffic_Calming)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "  Traffic Calming Vs. Severity",
       x = "Binned Severity Values",
       y = "Traffic Calming")

newDF1$dbl_col_binned <- cut(newDF1$Severity, breaks = 5, labels = FALSE)
agg_data <- aggregate(Traffic_Signal ~ dbl_col_binned, data = newDF1, FUN = mean)

plot2a <- ggplot(agg_data, aes(x = factor(dbl_col_binned), y = Traffic_Signal)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Traffic Signals Vs. Severity",
       x = "Binned Severity Values",
       y = "Traffic Signals")



newDF1$dbl_col_binned <- cut(newDF1$Severity, breaks = 5, labels = FALSE)
agg_data <- aggregate(Crossing ~ dbl_col_binned, data = newDF1, FUN = mean)

plot3a <- ggplot(agg_data, aes(x = factor(dbl_col_binned), y = Crossing)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Crossings Vs. Severity",
       x = "Binned Severity Values",
       y = "Crossings")


grid.arrange(plot1a, plot2a, plot3a, ncol=3)


```
