---
title: "STAT167 Final Project - Spring 2023"
authors: "Ryan Solanki, Jake Merrill, Girum Yaye, Harrison Chow, Shuqiao Yu"
date: "2023/5/12"
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: 3
---

#STAT 167 Final Project - Spring 2023

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Required libraries
```{r}
library(tidyverse)
library(CatEncoders)
library(gridExtra)
library(dplyr)
library(splitstackshape)
library(boot)
```

##Loading the dataset of US car data
```{r}
# Load car data
set.seed(167)
car_data <- read_csv("car_prices.csv")
head(car_data,5)
```

## Data Cleaning
```{r}
# Drop NA values in dataset
car_data <- car_data %>% drop_na()

# Remove unnecessary variables 
car_data <- subset(car_data, select = -c(vin, seller, saledate))

head(car_data, 5)
```

## Exploratory Data Analysis
```{r}
#shows selling price vs condition for each year
ggplot(data = car_data) +
  geom_point(mapping = aes(x = condition, y = sellingprice)) +
  facet_wrap(~ year) + 
  labs(title = "Selling Price vs Condition by Year")
```

```{r}
#adds column called diff1 that calculates the differences between sellingprice and MMR
#selects top 10 differences by make of the car
car_data1 <- car_data
car_data1$diff = car_data1$sellingprice - car_data1$mmr
car_data1 <- car_data1 %>%
  group_by(make) %>%
  arrange(desc(diff)) %>%
  summarise(diff1 = mean(diff))

#plots top 20 differences by make
ggplot(data = car_data1) +
  geom_point(mapping = aes(x = diff1, y = make)) +
  labs(y = "Make",x = "Difference Between Selling Price & MMR", title = "Make vs Diference in Selling Price & MMR")
```
  
```{r}
#clean dataset to help with dupe removal
dataset_no_duplicates <- car_data
dataset_no_duplicates$make <- tolower(dataset_no_duplicates$make)
dataset_no_duplicates$model <- tolower(dataset_no_duplicates$model)

#remove duplicate rows to only contain singular makes
dataset_no_duplicates <- dataset_no_duplicates[!duplicated(dataset_no_duplicates$model), ]

#Stratified sampling due to large dataset size
smaller_dataset <- stratified(dataset_no_duplicates, "make", size = 0.05)

#Relationship between selling price and a car's make and model 
 ggplot(smaller_dataset, aes(x = make, y = sellingprice, color = model)) +
  geom_point() +
  labs(x = "Make", y = "Selling Price", title = "Selling Price of Cars by Make and Model") +
  theme_minimal(base_size = 8) + # change the base_size to a smaller value
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
selling_prices_high <- car_data %>%
  group_by(make) %>%
  arrange(desc(sellingprice)) %>%
  head(2000)
selling_prices_high <- selling_prices_high %>% drop_na()

ggplot(data = selling_prices_high) +
  geom_col(mapping = aes(x = make, y = sellingprice, fill = body)) +
  labs(x = "make", y = "selling price", title = "Highest Selling Prices vs. Car Type") +
  coord_flip()

selling_prices_low <- car_data %>%
  group_by(make) %>%
  arrange(desc(-sellingprice)) %>%
  head(2000)
selling_prices_low <- selling_prices_low %>% drop_na()

ggplot(data = selling_prices_low) +
  geom_col(mapping = aes(x = make, y = sellingprice, fill = body)) +
  labs(x = "make", y = "selling price", title = "Lowest Selling Prices vs. Car Type") +
  coord_flip()
```


```{r}
#Relationship between odometer miles and selling price
ggplot(car_data, aes(x = odometer, y = sellingprice)) +
  geom_point() +
  labs(x = "Odometer Miles", y = "Selling Price", title = "Odometer Miles and Selling Price") +
  theme_minimal()
```

## Multiple Linear Regression
```{r}
# Transform non numeric values to numeric for Linear regression using label encoder
regression_data <- car_data

# Convert car make to numeric values
lab_enc = LabelEncoder.fit(regression_data$make)
regression_data$make <- transform(lab_enc, regression_data$make)

# Convert car model to numeric values
lab_enc = LabelEncoder.fit(regression_data$model)
regression_data$model <- transform(lab_enc, regression_data$model)

# Convert car trim to numeric values
lab_enc = LabelEncoder.fit(regression_data$trim)
regression_data$trim <- transform(lab_enc, regression_data$trim)

# Convert car body style to numeric values
lab_enc = LabelEncoder.fit(regression_data$body)
regression_data$body <- transform(lab_enc, regression_data$body)

# Convert car transmission type to numeric values
lab_enc = LabelEncoder.fit(regression_data$transmission)
regression_data$transmission <- transform(lab_enc, regression_data$transmission)

# Convert state to numeric values
lab_enc = LabelEncoder.fit(regression_data$state)
regression_data$state <- transform(lab_enc, regression_data$state)

# Convert car exterior color to numeric values
lab_enc = LabelEncoder.fit(regression_data$color)
regression_data$color <- transform(lab_enc, regression_data$color)

# Convert car interior color to numeric values
lab_enc = LabelEncoder.fit(regression_data$interior)
regression_data$interior <- transform(lab_enc, regression_data$interior)

head(regression_data, 5)
```

```{r}
# Multiple Linear Regression Model to predict selling price using forward selection

# base model with no explanatory variables
baseModel <- lm(sellingprice ~ 1, regression_data)

# full model with all explanatory variables
fullModel <- lm(sellingprice ~ ., regression_data)

# do stepwise to find out the best linear regression model
stepModel <- step(baseModel, scope = list(upper = fullModel, lower = ~1), direction = "forward")
summary(stepModel)

# Normal MLR model without forward selection
mlr <- lm(sellingprice ~ . -model, regression_data)
summary(mlr)
```

```{r}
# k fold cross validation
glm.fit <- glm(sellingprice ~ mmr + condition + year + odometer + state + transmission + trim + color + interior + body + make, data = regression_data)

MSE.cv.10 <- cv.glm(regression_data, glm.fit, K = 10)$delta[1]
MSE.cv.10
```

```{r}
# Residual plot used to see if relationship is linear
diagnostics <- tibble(predictions = mlr$fitted.values, residuals = mlr$residuals)

ggplot(diagnostics, aes(x = predictions, y = residuals)) +
geom_point() + geom_smooth(se = F)+
geom_hline(yintercept = 0, linetype = 2)
```
